replicaCount: 1
environment: development
image:
  repository: acrfinalprojectrafa.azurecr.io/frontend_dev
  tag: 1.0.2
imagePullSecret: acr-secret
resources:
  requests:
    memory: "200Mi"
    cpu: "100m"
  limits:
    memory: "400Mi"
    cpu: "300m"

