name: Build and Push to ACR

on:
  workflow_call:
    secrets:
      ARM_CLIENT_ID:
        required: true
      ARM_CLIENT_SECRET:
        required: true
      ARM_TENANT_ID:
        required: true
      ARM_SUBSCRIPTION_ID:
        required: true
    inputs:
      acr_login_server:
        required: true
        type: string

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          repository: stemdo-labs/final-project-gestion-orquestas-backend-RafaGll
      
      - name: print
        run: ls -la

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          client-secret: ${{ secrets.ARM_CLIENT_SECRET }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}

      - name: Log in to ACR
        run: |
          az acr login --name ${{ secrets.acr_login_server }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.acr_login_server }}/frontend:latest .

      - name: Push Docker Image to ACR
        run: |
          docker push ${{ secrets.acr_login_server }}/frontend:latest
