name: Build and Push to ACR

on:
  workflow_call:
    inputs:
      client_id:
        required: true
        type: string
      client_secret:
        required: true
        type: string
      tenant_id:
        required: true
        type: string
      subscription_id:
        required: true
        type: string
      acr_login_server:
        required: true
        type: string

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: print
        run: ls -la

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ inputs.client_id }}
          client-secret: ${{ inputs.client_secret }}
          tenant-id: ${{ inputs.tenant_id }}

      - name: Log in to ACR
        run: |
          az acr login --name ${{ inputs.acr_login_server }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ inputs.acr_login_server }}/frontend:latest .

      - name: Push Docker Image to ACR
        run: |
          docker push ${{ inputs.acr_login_server }}/frontend:latest
