name: Build and Push to ACR (Frontend)

on:
  workflow_call:
    secrets:
      ARM_CLIENT_ID:
        required: true
      ARM_CLIENT_SECRET:
        required: true
      ARM_TENANT_ID:
        required: true
      ARM_SUBSCRIPTION_ID:
        required: true
    inputs:
      acr_login_server:
        required: true
        type: string

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          repository: stemdo-labs/final-project-gestion-orquestas-frontend-RafaGll
          ref: main

      - name: Extract Version from package.json
        id: extract_version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          client-secret: ${{ secrets.ARM_CLIENT_SECRET }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}

      - name: Log in to ACR
        run: |
          az acr login --name ${{ inputs.acr_login_server }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ inputs.acr_login_server }}/frontend:${{ env.VERSION }} .

      - name: Push Docker Image to ACR
        run: |
          docker push ${{ inputs.acr_login_server }}/frontend:${{ env.VERSION }}

      - name: Set job outputs
        id: set_outputs
        run: echo "image_url=${{ inputs.acr_login_server }}/frontend:${{ env.VERSION }}" >> $GITHUB_OUTPUT

    outputs:
      image_url: ${{ steps.set_outputs.outputs.image_url }}