name: Build and Push to ACR

on:
  workflow_call:
    secrets:
      client_id:
        required: true
      client_secret:
        required: true
      tenant_id:
        required: true
      subscription_id:
        required: true
      acr_login_server:
        required: true

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: print
        run: ls -la

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.client_id }}
          client-secret: ${{ secrets.client_secret }}
          tenant-id: ${{ secrets.tenant_id }}

      - name: Log in to ACR
        run: |
          az acr login --name ${{ secrets.acr_login_server }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.acr_login_server }}/frontend:latest .

      - name: Push Docker Image to ACR
        run: |
          docker push ${{ secrets.acr_login_server }}/frontend:latest
