name: Despliegue

on: workflow_dispatch

jobs:
  pre-deploy:
    name: Preparación del despliegue
    runs-on: [self-hosted, pruebas]
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
    steps:    
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Extract Version from package.json
        id: extract_version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "version=${VERSION}" >> $GITHUB_OUTPUT


  deploy:
    needs: pre-deploy
    uses: stemdo-labs/final-project-exercise-RafaGll/.github/workflows/ci.yml@workflow
    with:
      version: ${{ needs.pre-deploy.outputs.version }}
      deploy: frontend
    secrets:
      PAT: ${{ secrets.PAT }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}